### ISSUE TITLE
lxc-apt-install error

### ISSUE THREAD

**Issue by fedusiv** [kernelci/lava-docker#100]
I'm trying to run fastboot with lxc. 
I added 
RUN apt-get -y install lavacli
RUN apt-get -y install lava-lxc-mocker
to Dockerfile, cause without it I cant work with lxc.

And I received error after submit the job:
/var/lib/dpkg/lock problem
output: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/)

**Comment by montjoie** [comment]
Hello, LXC is hard to "mock" in docker, please try to use docker instead.
We are in the process to stop using LXC at all.
