### ISSUE TITLE
Python2.7 -> Python3 for lava-slave

### ISSUE THREAD

**Issue by ChristophRahn** [kernelci/lava-docker#101]
The update to 2019.07 containers from Lava has dropped Python2.7 support as a side effect. The scripts that are currently using Python2.7 imports should be changed as the lava-slave container does not work at the moment.

I have found and fixed problems in [start.sh](./lava-slave/scripts/start.sh) and [setdispatcherip.py](./lava-slave/scripts/setdispatcherip.py). I can open a PR for this, if you want.

**Comment by khilman** [comment]
Yes please.  PRs are welcome.
