### ISSUE TITLE
new udev device discovery for docker test jobs fails to work

### ISSUE THREAD

**Issue by slawr** [kernelci/lava-docker#126]
### Summary
LAVA [MR 1238](https://git.lavasoftware.org/lava/lava/-/merge_requests/1238) reworked the device handling in docker test shell jobs. The improvements include better support for udev device discovery of transient devices, e.g. fastboot device on reboot, so they are discovered and shared with the docker container specified in the job.

The support uses the utility lava-dispatcher-host which to work must be installed on the host. Currently lava-docker does not take account of this requirement and so such jobs will fail in some way. 

This may also be the case for jobs using LXC but has not been investigated.

I'm happy to send a PR to fix the issue in lava-docker but I have some questions about how lava-docker is working below before I can finalise it.

### Example failure
The following fastboot [test case](https://lava.genivi.org/scheduler/job/1216/definition#defline40) shows the issue in docker test jobs:
```
          - fastboot reboot-bootloader
          - fastboot devices
          - fastboot --set-active=a
```
The first host fastboot command will reboot the DUT. The third command passing --set-active will cause fastboot on the host to wait for the DUT to reappear. In the [failing case](https://lava.genivi.org/scheduler/job/1216#L243) LAVA fails to discover and share the DUT fastboot device after reboot into the test container.

Debugging by manually entering the container will show that the DUT has successfully rebooted and host and DUT can communicate via fastboot. So the issue appears to be limited to LAVA.

### Investigation
With the code changes rather than sharing a list of devices with the container when it is started, LAVA shares them dynamically via lava-dispatcher-host. lava-dispatcher-host relies on a [udev rule](https://git.lavasoftware.org/lava/lava/-/blob/master/lava_dispatcher_host/udev.py#L18) for udev discovery. In a current lava-docker installation lava-dispatcher-host is installed by the base linaro dispatcher [DockerFile](https://git.lavasoftware.org/lava/lava/-/blob/master/docker/lava-dispatcher/Dockerfile) and therefore into the Worker docker. The udev database shared into the Worker docker is insufficient for this to work (at least in my testing) and of course udev events do not appear in the Worker docker. This leads to the udev rule not being run.

I have discussed this with the LAVA devs on the lava-users mailing list. The developer of the changes has confirmed that lava-dispatcher-host needs to run on the host: https://lists.lavasoftware.org/pipermail/lava-users/2020-August/002593.html

The question then is how best to implement that in lava-docker?

The lava-dispatcher-host package, being new, only appears to be in debian in sid unstable:
https://packages.debian.org/search?suite=all&arch=any&mode=filename&searchon=names&keywords=lava-dispatcher-host

It of course is also in the LAVA source itself.

If lava-dispatcher-host is installed via the package then no other configuration is required. The udev rule is installed automatically. If it is installed from source then the rule needs to be installed [manually](https://git.lavasoftware.org/lava/lava/-/commit/6b52d23ed7e446c7f2d625aad56e6785809bcfb9?merge_request_iid=1296)

Personally I installed the debian package in the host and found this worked. After restarting udev and the worker container. [Successful test job](https://lava.genivi.org/scheduler/job/1221#L243)

One noted downside is that as lava-dispatcher-host is running on the host the rediscovery of the device is not logged in the job log. Not so good for debugging, but an acceptable compromise I think. At least until better solutions appear.

So returning to the question of what to do in lava-docker. This could be a simple change to the readme.md to add lava-dispatcher-host to the list of required packages. However [deploy.sh](https://github.com/kernelci/lava-docker/blob/master/deploy.sh#L8) removes all udev rules with lava in the name from the host:
```
$BEROOT rm /etc/udev/rules.d/*lava*rules
```

I could see you removing potentially old lava-docker installed rules but I wonder why you are deleting all rules with lava in the name. Could you explain why that is so I can figure out what the best change to make is?

**Comment by montjoie** [comment]
Hello

Thanks for your report.
I have started to work on it: https://github.com/kernelci/lava-docker/pull/127
In fact the naming of udev rules changed at start of project, so we remove all lava rules which at that time could be only ours.
This fact is now obsolete.

**Comment by slawr** [comment]
> I have started to work on it: #127

OK thanks. I will leave the PR to you then.

> In fact the naming of udev rules changed at start of project, so we remove all lava rules which at that time could be only ours.
> This fact is now obsolete.
Thank you for the explanation. I was uncertain of the history from the commit messages.

Just an idea but if the lava-docker created rules were prefixed with 'lava-docker' in the filename that might help you distinguish the lava-docker specific rules to delete, short of maintaining a list.

**Comment by obbardc** [comment]
looks like the PR was merged - can you confirm whether the problem went away @slawr ?

**Comment by slawr** [comment]
> looks like the PR was merged - can you confirm whether the problem went away @slawr ?

Hi, uncertain when in the coming days I will get to try the merged fix. I'm blocked currently from taking the LAVA master branch tip or 2020.08 due to a recent LAVA commit that requires a LAVA Master (server) update. As I maintain the LAVA Worker only in my instance I must coordinate with the Master maintainer to re-base. So I'll use my local fix until that happens.

But in terms of the fix then if you need the new feature (jobs which use docker containers for testing and have devices that come and go, e.g. fastboot) then I see no reason why Corentin's commit doesn't address the issue. You need the lava-dispatcher-host package installed on the host and lava-docker deploy.sh must not delete the udev rule it installs.

**Comment by slawr** [comment]
Cherry picked script change and confirmed @montjoie PR addresses this issue. Closing issue as fixed.
