### ISSUE TITLE
Checks for x86_64 host as amd64 with uname -m

### ISSUE THREAD

**Issue by broonie** [kernelci/lava-docker#146]
When checking to see if we are running on an x86_64 host the lava-slave Dockerfile does

  if [ "$(uname -m)" != "amd64" ]; then

but uname -m returns the kernel's idea of the architecture which is x86_64 not amd64 causing the check to fail unexpectedly. 

This currently fails since the LAVA version is 2021.03 which predates the last Debian release, causing apt to complain about the rename from stable to oldstable when doing dpkg --add-architecture.

**Comment by montjoie** [comment]
Fixed in master. Thanks for reporting.
