### ISSUE TITLE
Upgrade to 2022.03 fails because of postgresql error during `docker-compose up`

### ISSUE THREAD

**Issue by QSchulz** [kernelci/lava-docker#150]
I cannot update from 2021.03 to 2022.03 because my master node (named lava-server) fails to boot with the following error message:
```
lava-server_1     | Starting postgresql
lava-server_1     | Starting PostgreSQL 13 database server: mainError: /var/lib/postgresql/13/main is not accessible or does not exist ... failed!
```
@montjoie reported to have had the same issue when `persistent_db` is set to True in the master node and removing it "fixes" the issue.

Updating with persistent database is therefore currently not supported as far as I understood.

**Comment by montjoie** [comment]
You could udpate until a major postgresql version change.
I will update documentation on this.

**Comment by montjoie** [comment]
Documentation update via https://github.com/kernelci/lava-docker/pull/172
