### ISSUE TITLE
RISC-V qemu cannot be executed

### ISSUE THREAD

**Issue by jiewu9823** [kernelci/lava-docker#156]
RISC-V qemu can be execute with the following command in lava-slave docker container. 

````
$ qemu-system-riscv64 -M virt -m 256M -nographic -kernel inlinepath/Image -drive file=inlinepath/rootfs.img,format=raw,id=hd0  -device virtio-blk-device,drive=hd0 -append "root=/dev/vda rw console=ttyS0"
````

but it cannot be executed in lava job and prompt machine type does not support if=ide bus=0 unit=0

<img width="604" alt="08" src="https://user-images.githubusercontent.com/89007492/198540472-cd1d3e32-3ff5-453b-a760-2ee80db26041.png">

**Comment by montjoie** [comment]
Hello

This is unrelated to lava-docker.
You need to specify guestfs_interface: virtio in job context.
By default LAVA add the disk as ide if you didnt specify it.

Regards

**Comment by jiewu9823** [comment]
Hi
RISC-V qemu can be execute successfully after specifying guestfs_interface: virtio in job context.
Thanks a lot.


> Hello
> 
> This is unrelated to lava-docker. You need to specify guestfs_interface: virtio in job context. By default LAVA add the disk as ide if you didnt specify it.
> 
> Regards
