### ISSUE TITLE
Is there a way to post job in lava-docker to kernelci-docker?

### ISSUE THREAD

**Issue by BIRooter** [kernelci/lava-docker#168]
I defined a job in lava-docker as following:

metadata:
  device.type: qemu_x86_64
  git.branch: linux-5.4.y
  git.commit: f015b86259a520ad886523d9ec6fdb0ed80edc38
  job.arch: x86_64
  job.build_environment: gcc-8
  kernel.defconfig: x86_64_defconfig
  kernel.defconfig_full: x86_64_defconfig
  kernel.tree: stable
  test.plan: baseline
  git.describe: v5.4.40
  git.url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
  image.url: https://kgithub.com/montjoie/lava-healthchecks-binary/blob/master/stable/linux-5.4.y/v5.4.40/x86_64/x86_64_defconfig/gcc-8/
  job.dtb_url: None
  job.file_server_resource: stable/linux-5.4.y/v5.4.40/x86_64/x86_64_defconfig/gcc-8
  job.initrd_url: https://kgithub.com/montjoie/lava-healthchecks-binary/blob/master/images/rootfs/buildroot/kci-2019.02-9-g25091c539382/x86/baseline/rootfs.cpio.gz?raw=true
  job.kernel_image: bzImage
  job.kernel_url: https://kgithub.com/montjoie/lava-healthchecks-binary/blob/master/stable/linux-5.4.y/v5.4.40/x86_64/x86_64_defconfig/gcc-8/bzImage?raw=true
  job.modules_url: https://kgithub.com/montjoie/lava-healthchecks-binary/blob/master/stable/linux-5.4.y/v5.4.40/x86_64/x86_64_defconfig/gcc-8/modules.tar.xz?raw=true
  job.name: stable-linux-5.4.y-v5.4.40-x86_64-x86_64_defconfig-gcc-8-no-dtb-qemu_x86_64-baseline_qemu
  job.nfsrootfs_url: None
  job.original: None  
  kernel.arch_defconfig: x86_64-x86_64_defconfig
  kernel.endian: little
  kernel.version: v5.4.40
  platform.dtb: None
  platform.dtb_short: None
  platform.fastboot: false
  platform.mach: qemu
  test.plan_variant: baseline_qemu
  
notify:
  criteria:
    status: complete
  callbacks:
    - url: http://192.168.122.208:8000/api/v0.2/jobs/{LAVA_JOB_ID}/tests/?format=json
      method: GET
    - url: http://192.168.122.208:8081/callback/lava/test?lab_name=lab-01&status={STATUS}&status_string={STATUS_STRING}
      method: POST
      dataset: all
      token: kernelci-token
      content-type: json

device_type: qemu

context:
  arch: x86_64
  cpu: qemu64
  guestfs_interface: ide
  extra_kernel_args: "no_timer_check"

job_name: "lava-kernelci(kgithub) complete demo"
timeouts:
  job:
    minutes: 20
  action:
   minutes: 18
  actions:
    power-off:
      seconds: 30
priority: medium
visibility: public

actions:
- deploy:
    timeout:
      minutes: 10
    to: tmpfs
    os: oe
    images:
      kernel:
        image_arg: '-kernel {kernel} -append "console=ttyS0,115200 root=/dev/ram0 debug verbose console_msg_format=syslog"'
        url: http://192.168.122.208:9900/bzImage
      ramdisk:
        image_arg: '-initrd {ramdisk}'
        url: http://192.168.122.208:9900/rootfs.cpio.gz

- boot:
    timeout:
      minutes: 5
    method: qemu
    media: tmpfs
    prompts:
      - '/ #'

- test:
    timeout:
      minutes: 5
    definitions:
    - repository:
        metadata:
          format: Lava-Test Test Definition 1.0
          name: baseline
          description: "baseline test plan"
          os:
            - debian
          scope:
            - functional
          environment:
            - lava-test-shell
        run:
          steps:
            - >
                for level in warn err; do
                  dmesg --level=$level --notime -x -k > dmesg.$level
                done
            - >
                for level in crit alert emerg; do
                  dmesg --level=$level --notime -x -k > dmesg.$level
                  test -s dmesg.$level && res=fail || res=pass
                  count=$(cat dmesg.$level | wc -l)
                  lava-test-case $level \
                    --result $res \
                    --measurement $count \
                    --units lines
                done
            - cat dmesg.emerg dmesg.alert dmesg.crit dmesg.err dmesg.warn
      from: inline
      name: dmesg
      path: inline/dmesg.yaml

- test:
    timeout:
      minutes: 5
    definitions:
    - repository:
        metadata:
          format: Lava-Test Test Definition 1.0
          name: baseline
          description: "baseline test plan"
          os:
            - debian
          scope:
            - functional
          environment:
            - lava-test-shell
        run:
          steps:
            - export PATH=/opt/bootrr/helpers:$PATH
            - cd /opt/bootrr && sh helpers/bootrr-auto
      lava-signal: kmsg
      from: inline
      name: bootrr
      path: inline/bootrr.yaml

Its test result can be post to kernelci-docker and displayed in kernelci-frontend. 

But kernelci-front will not list the job.

Is there any way to do that?

**Comment by montjoie** [comment]
I am sorry but this is unrelated to lava-docker, but more to LAVA+kernelCI frontend

**Comment by BIRooter** [comment]
OK, thank you!
