### ISSUE TITLE
ImportError: No module named 'yaml'

### ISSUE THREAD

**Issue by kuzetsa** [kernelci/lava-docker#31]
This may be a documentation bug.

I'm not sure:

```
kuzetsa@da7728a3 ~/kernelci/lava-docker $ pip show pyyaml
Name: PyYAML
Version: 3.13
Summary: YAML parser and emitter for Python
Home-page: http://pyyaml.org/wiki/PyYAML
Author: Kirill Simonov
Author-email: xi@resolvent.net
License: MIT
Location: /home/kuzetsa/.local/lib/python2.7/site-packages
Requires: 
```

pyyaml-3.13 is installed, and yet:

```
kuzetsa@da7728a3 ~/kernelci/lava-docker $ ./lavalab-gen.py 
Traceback (most recent call last):
  File "./lavalab-gen.py", line 6, in <module>
    import yaml
ImportError: No module named 'yaml'
```

---

hostname: da7728a3 is running a recent install of Ubuntu 18.04 LTS,

the PyYAML version which was installed via pip:

https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)

--- 

updated to add:

```
kuzetsa@da7728a3 ~ $ env python --version
Python 3.5.5

kuzetsa@da7728a3 ~ $ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

after installing python3 version:

```
sudo apt-get install python3-pip && pip3 install pyyaml && pip3 show pyyaml

Name: PyYAML
Version: 3.13
Summary: YAML parser and emitter for Python
Home-page: http://pyyaml.org/wiki/PyYAML
Author: Kirill Simonov
Author-email: xi@resolvent.net
License: MIT
Location: /home/kuzetsa/.local/lib/python3.6/site-packages
Requires: 
```
... the error persists

**Comment by aliceinwire** [comment]
what about upgrading your pip version?
pip --upgrade pip --user

**Comment by kuzetsa** [comment]
looks like I was able to install dev-python/pyyaml  
(*using prefixed installation of gentoo*)  
and I'm now able to run normally:

```
kuzetsa@da7728a3 ~/kernelci/lava-docker $ ./lavalab-gen.py 
Handle master1

Found tokens
        Add token for admin in admin-0
Handle lab-slave-0
        Found qemu-01 on lab-slave-0
```

I don't know how to use ubuntu, but fortunately that's not an issue today for me.

probably someone else who understands that OS can troubleshoot. At this point I just completely uninstalled the ubuntu pip because the dev-python/pyyaml isn't tied to ubuntu's tooling anyway. It's not a solution which will work for normal ubuntu users, I think.

---

update:

I'm no longer experiencing the error, but I think README.md has a minor documentation bug: there is not any mention of pyyaml will need installed if it isn't already available in order to run lavalab-gen.py  without error

**Comment by aliceinwire** [comment]
nice that you could fix the problem.
Probably would be nice to have a requirements.txt file with the needed python dependencies.

**Comment by kuzetsa** [comment]
that makes sense. either that, or I'm thinking it could fit into the existing "Prerequisites" section of the main README.md - whatever the case, a one-liner pull request for a documentation fix shouldn't be too hard.

some time this weekend or maybe today I'm intending to spin up a default debian stretch instance as it is the main / officially supported distro for both lava and lava-docker. If I find working yaml support "out of the box", I'll check which version of pyyaml is in use for the fresh OS install, or if it needs installed I'll see which one(s) can fulfill the requirement.
