### ISSUE TITLE
Device registration from remote worker does not work

### ISSUE THREAD

**Issue by germaino** [kernelci/lava-docker#41]
Hi,
If your boards.yml has both local and remote worker and devices are attached to the remote worker, settings dictionary device from the remote workerwill  fail
The following command from setup.sh on the slave

lavacli --uri <master uri> devices dict <my device> /root/devices/lab-slave-1/<my device>.jinja2 trigger the following error:
Unable to call 'devices.dict': <ProtocolError for ... ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))>

**Comment by montjoie** [comment]
Please give your full boards.yaml
