### ISSUE TITLE
It is too slow when Building lab-slave-0 Step 1/32 : FROM baylibre/lava-slave-base:latest?

### ISSUE THREAD

**Issue by rambollee** [kernelci/lava-docker#43]
Hi,all. I am installing the lava for the first time. 

During docker-compose build,  the process below is too slow, 

Building lab-slave-0
Step 1/32 : FROM baylibre/lava-slave-base:latest
latest: Pulling from baylibre/lava-slave-base

I waited it for serveral day,  and  restart this cmd for many times.  It also stop there.
Maybe it is due to my  network condition,  which is out of my control.
Could anyone have some better idea to avoid it ?(Building master1 successed)
THX.

**Comment by khilman** [comment]
You could try to build those images yourself, the repo contains the Dockerfiles.  e.g.

> cd lava-slave-base
> docker build -t baylibre/lava-slave-base .

This will build a local version of the images needed so when you do the `docker-compose build` it will use your locally build version instead of trying to pull from docker hub.
