### ISSUE TITLE
tftp fails with beaglebone black health checks

### ISSUE THREAD

**Issue by RobertAJMarshall** [kernelci/lava-docker#45]
I'm attempting to use lava-docker and get the builds from a local board at desk VM but I'm getting problems with U-Boot timing out https://paste.baserock.org/oxebuvinic I'm using our own connect script for talking to the beaglebone black which installs ok. I've also tried with the docker image default health check which gives me the same problem

**Comment by khilman** [comment]
This looks like a lab/networking issue, or possible a beaglebone that needs a u-boot upgrade.  This isn't something lava-docker can solve.

**Comment by mungaip** [comment]
I encountered a very similar issue. It seems to be a networking issue.

Firstly, the serverip set is the container's IP for the bridged interface with the host. This can be seen from the host machine, but no external device can see it or ping it. 

In order for external devices to be able to access the container, the virtual ethernet interface of the container has to be up. For some reason, if the serverip is set to the same IP as the interface on the host that the DUT is connected to, then tftp works. (eg. if the DUT is connected to the eth2 interface on the host, it id the IP of the eth2 interface). I have tried setting serverip to the veth of the docker container (which would be the more logical solution), but it just times out in the same way mentioned in the original issue, so it looks like the request doesn't get through to the tftp server.

The variable SERVER_IP is set somewhere within the docker environment to match the container's IP address for the host-only/bridged network. I think there may be a change that will need to be made in lava-docker to solve this issue.

**Comment by mungaip** [comment]
I have just seen that the "dispatcher_ip" variable in boards.yaml should set this value (with an explanation of why it is the host's IP address), but it gets overridden meaning the healthcheck will fail at this stage every time.

So this is an issue with lava not using the dispatcher ip rather than a tftp issue.

**Comment by mungaip** [comment]
I have asked on the mailing list, and the dispatcher ip needs to be set for each worker on the master instance. This should be done by altering the [dispatcher.yaml file](https://git.lavasoftware.org/lava/lava/blob/master/etc/dispatcher.yaml)

Here are the links as to what to do:
[https://master.lavasoftware.org/static/docs/v2/simple-admin.html#lava-configuration-files](https://master.lavasoftware.org/static/docs/v2/simple-admin.html#lava-configuration-files)
[https://master.lavasoftware.org/static/docs/v2/pipeline-admin.html#extra-dispatcher-configuration](https://master.lavasoftware.org/static/docs/v2/pipeline-admin.html#extra-dispatcher-configuration)

I added the configuration onto the master by using lavacli (the lava API)

**Comment by mungaip** [comment]
I think the issue comes down to the setdispatcherip.py script not working as it should. The master is expecting a yaml file from the API opposed to the string that is parsed to it by the API in the script.

**Comment by manojtiwary22** [comment]
@patrykmungai  What should be the dispatcher ip? and should I have to create file in /etc/lava-server/dispatcher.d also ?
can you tell what changes I have to do in both slave and master container .

Thank you

**Comment by mungaip** [comment]
@manojtiwary22, the dispatcher ip is the network that your DUTs are connected to. 
All the issues I faced were solved by understanding the boards.yaml file. You have to have as a minimum everything in the initial boards.yaml file included in this repository.  And that should set everything up for you. My mistake was trying to remove things from the file (eg. only include the slaves section as I didn't want to create a master). This results in the setup scripts aborting before everything is setup meaning the container(s) don't work as expected.

**Comment by montjoie** [comment]
https://github.com/Muuselabs/fw-issues/issues/82

**Comment by montjoie** [comment]
No change since 3 years
