### ISSUE TITLE
the job is not schduled with the last docker build image (docker --pull --no-cache blablabla)

### ISSUE THREAD

**Issue by leiyang** [kernelci/lava-docker#6]
I add the qemu device type and qemu01 target from the lava website, and then submit the first job from
https://validation.linaro.org/static/docs/v2/first-job.html#submit-first-job

then I click "all jobs" it tells 
500 Internal Server Error
context must be a dict rather than RequestContext.

Oops, something has gone wrong!

and then I check "all devices" I find no job is running on the qemu01 device

**Comment by EmbeddedAndroid** [comment]
@leiyang can you try using the this container built off our kernelci-v2 branch? https://hub.docker.com/r/kernelci/lava-docker-v2/tags/ it will correctly install a qemu target that has been tested and known to run jobs properly.

**Comment by ywangwrs** [comment]
Looks like the latest version has an issue:
root@172239087345:/# lava-tool auth-add http://<userid>@localhost
Paste token for http://<userid>@localhost/RPC2/: 
ERROR: Token rejected by server for user <userid>.

**Comment by montjoie** [comment]
No change since 4 years
