### ISSUE TITLE
Healthcheck is failing

### ISSUE THREAD

**Issue by manojtiwary22** [kernelci/lava-docker#60]
Hi guys,

I've have added bcm2837-rpi-3-b device to lava scheduler. whenever the health check runs it is failing . I think it has something to do with networking. so please help me resolve the issue. below i've attached screenshots of test log.
 And can anyone help me with device dictionary for my raspberrypi3 board.
Thank you.

![screenshot from 2018-10-31 10-07-45](https://user-images.githubusercontent.com/44599935/47766636-c54c2480-dcf5-11e8-94e3-eb47498e0e69.png)
![screenshot from 2018-10-31 10-08-30](https://user-images.githubusercontent.com/44599935/47766639-caa96f00-dcf5-11e8-9e93-82d974847f9e.png)

**Comment by khilman** [comment]
It appears your rpi3 does not have internet access.
