### ISSUE TITLE
kernelci-v2's README seems outdated

### ISSUE THREAD

**Issue by sangorrin** [kernelci/lava-docker#7]
"Where LAVA_SERVER_IP is the IP of your Docker host.": there is no LAVA_SERVER_IP on the command line. Only a LAVA_API_TOKEN variable, and it is not clear what to do with that one either.

EDIT: "kernelci/lava-docker-v2:latest" should be "lava:latest"

**Comment by EmbeddedAndroid** [comment]
I think you've mixed up the two lava-docker projects. This project is lava-docker, which will deploy lava-server and lava-dispatcher. The README on the kernelci-v2 branch doesn't contain any references to LAVA_SERVER_IP:

https://github.com/kernelci/lava-docker/blob/kernelci-v2/README.md

The project which references LAVA_SERVER_IP is lava-slave-docker, which is a dumb dispatcher installer, with no master:

https://github.com/kernelci/lava-slave-docker/blob/master/README.md

The example command in the README is also correct, and specifies two variables to use. LAVA_SERVER the IP for your master, and LAVA_SERVER_IP the variable which represents your host IP address. I'll admit the naming of these variables is a bit confusing. 

kernel-cil/lava-docker-v2:latest is correct, as kernel-ci/lava-docker:2017.07 is the base LAVA installation. kernel-ci/lava-docker-v2:latest will perform the setup needed to run our kernelci qemu jobs, but inherits from the base image kernel-ci/lava-docker:2017.07.

**Comment by sangorrin** [comment]
Thanks, I didn't know that the dispatcher was separated. 

However, LAVA_SERVER_IP does indeed appear in the README.md as well as in the setup.sh script.
https://github.com/kernelci/lava-docker/blob/kernelci-v2/README.md
https://github.com/kernelci/lava-docker/blob/kernelci-v2/scripts/setup.sh

I can't find any LAVA_SERVER variable, am I missing something? do you mean the LAVA_MASTER variable in the lava-slave-docker project?

Also, I think that kernel-cil/lava-docker-v2:latest is incorrect. The correct one is lava:latest (notice that in the README the build command is: sudo docker build -t lava .)

**Comment by EmbeddedAndroid** [comment]
I see your point now about LAVA_SERVER_IP, that was probably a copy and paste mistake. I'll update the README to reflect the proper config.

LAVA_SERVER variable is only used for lava-slave-docker project.

I will add two sections to clarify your point. kernel-ci/lava-docker-v2:latest is the correct tag if you want to use the prebuilt images, however your right, if you've built the image locally lava:latest is correct.
