### ISSUE TITLE
LAVA doesn't accept proxy env.yaml file

### ISSUE THREAD

**Issue by mungaip** [kernelci/lava-docker#79]
Hello,

When I add my proxy environment to the boards.yaml [file](https://pastebin.com/f9qgs52f), I get the following error when LAVA is to run a healthcheck on the qemu device:
"Infrastructure error: Cannot open '/etc/lava-server/dispatcher.d/lab-slave-0/env.yaml': Not a valid YAML file".
Looking on the master container, the env.yaml file generated looks like:
overrides:
  {'http_proxy': 'http://XXX:YYY'}
  {'https_proxy': 'http://XXX:YYY'}
  {'ftp_proxy': 'http://XXX:YYY'}

opposed to 
overrides:
  http_proxy: http://XXX:YYY
  https_proxy: http://XXX:YYY
  ftp_proxy: http://XXX:YYY

I'm new to python so I'm not sure exactly how to change the lavalab_gen.py file in order to get the correct output.

**Comment by montjoie** [comment]
you need to protect the line with quotes.
try to add "http_proxy: http:////"

**Comment by mungaip** [comment]
Thank you @montjoie
