### ISSUE TITLE
Building lab-slave-0 fails @ apt-get update

### ISSUE THREAD

**Issue by ChristophRahn** [kernelci/lava-docker#97]
When I try the default build of the slave container I get the following error during `apt-get update`:

    E: Could not open file /var/lib/apt/lists/deb.debian.org_debian_dists_stretch-backports_main_binary-amd64_Packages.diff_Index - open (2: No such file or directory)
    ERROR: Service 'lab-slave-0' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 100

I do not know exactly why this fails, since the file is present in the [ftp mirror](http://ftp.debian.org/debian/dists/stretch-backports/main/binary-amd64/Packages.diff/), maybe redirecting fails? Anyway I managed to fix this by adding this command to the slave Dockerfile, but it is probably a better idea to fix this in the base container.

    7 RUN echo "deb https://deb.debian.org/debian/ stretch main contrib non-free \
      deb https://deb.debian.org/debian/ stretch-updates main contrib non-free \ 
      deb https://deb.debian.org/debian-security/ stretch/updates main contrib non-free \
      deb https://deb.debian.org/debian/ stretch-backports main contrib non-free" > /etc/apt/sources.list

Updates are then downloaded from `https://cdn-aws.deb.debian.org/debian` instead of `http://deb.debian.org/debian`.

**Comment by slawr** [comment]
Thanks for reporting this Christoph. I have also seen this error building on Debian 9.

**Comment by ChristophRahn** [comment]
I will close this, as I already closed the related PR #98. This is fixed by 2019.07 upgrade.
